// <auto-generated />
using System;
using LocalEnv.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalEnv.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230106155920_parameter-name")]
    partial class parametername
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("LocalEnv.Model.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinaryPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Agent");
                });

            modelBuilder.Entity("LocalEnv.Model.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("TesterPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("LocalEnv.Model.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Parameter");
                });

            modelBuilder.Entity("LocalEnv.Model.ParameterRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId");

                    b.ToTable("ParameterRange");
                });

            modelBuilder.Entity("LocalEnv.Model.TestcaseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("TestcaseResult");
                });

            modelBuilder.Entity("LocalEnv.Model.Agent", b =>
                {
                    b.HasOne("LocalEnv.Model.Game", null)
                        .WithMany("Agents")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("LocalEnv.Model.Parameter", b =>
                {
                    b.HasOne("LocalEnv.Model.Game", null)
                        .WithMany("Parameters")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("LocalEnv.Model.ParameterRange", b =>
                {
                    b.HasOne("LocalEnv.Model.Parameter", null)
                        .WithMany("Ranges")
                        .HasForeignKey("ParameterId");
                });

            modelBuilder.Entity("LocalEnv.Model.TestcaseResult", b =>
                {
                    b.HasOne("LocalEnv.Model.Agent", null)
                        .WithMany("TestcaseResults")
                        .HasForeignKey("AgentId");
                });

            modelBuilder.Entity("LocalEnv.Model.Agent", b =>
                {
                    b.Navigation("TestcaseResults");
                });

            modelBuilder.Entity("LocalEnv.Model.Game", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("LocalEnv.Model.Parameter", b =>
                {
                    b.Navigation("Ranges");
                });
#pragma warning restore 612, 618
        }
    }
}
